# Generated by Django 2.0.13 on 2019-10-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='send_шessages',
            new_name='send_messages',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пpoшeл активацию?'),
        ),
    ]
